# Site Settings
title: Esporo
tagline: A comunidade brasileira de Spore
description: >-
  Comunidade para jogadores de Spore, com conteúdos personalizados para download; tutoriais; fóruns de discussão e suporte; e as últimas notícias sobre o jogo.
logo: "/assets/images/logo.png"

lang: pt-BR
timezone: "America/Sao_Paulo"

email: contato@esporo.net
url: "https://esporo.net"
baseurl: ""

# Build settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "gaboo"

permalink: "/:year/:month/:title/"

keep_files:
  - favicon.ico
  - uploads
  - assets/fonts
  - assets/icons
  - assets/images
  - assets/js
  
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-compose

# Plugin: jekyll-paginate
paginate: 5
paginate_path: "/pagina/:num/"
seo_paginator_message: "Página %<current>s de %<total>s / "

# Plugin: jekyll-seo-tag
google_site_verification: "HvEDdWfesPnf99AxWv1yVL_bZfKiGp9XYmGcVz-ZJS4"

twitter:
  card: summary
  username: esporo

social:
  name: Esporo
  links:
    - https://twitter.com/esporo
    - https://www.youtube.com/user/esporotv
    - https://www.facebook.com/esporo

# Plugin: jekyll-archives
jekyll-archives:
  enabled:
    - tags
    - year
    - month
  layout: "archive"
  slug_mode: default
  permalinks:
    tag: "/tags/:name/"
    year: "/:year/"
    month: "/:year/:month/"
